on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  my_job:
    name: test runner
    runs-on: ubuntu-latest
    steps:
      - name: inspect runner
        run: | 
          sudo mount
          sudo df -h
          sudo cat /proc/cpuinfo
          sudo cat /proc/meminfo
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: inspect runner
        run: | 
          sudo mount
          sudo df -h
          sudo cat /proc/cpuinfo
          sudo cat /proc/meminfo
